"""sprint2 rag documento_fragmento_farmacologico

Revision ID: 076601647d34
Revises: 905aceff5f41
Create Date: 2026-06-21 22:21:39.775781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '076601647d34'
down_revision: Union[str, None] = '905aceff5f41'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_farmacologico',
    sa.Column('id_documento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=True),
    sa.Column('fuente', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('hash_archivo', sa.String(length=64), nullable=False),
    sa.Column('estado_procesamiento', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_index(op.f('ix_documento_farmacologico_hash_archivo'), 'documento_farmacologico', ['hash_archivo'], unique=True)
    op.create_index(op.f('ix_documento_farmacologico_id_documento'), 'documento_farmacologico', ['id_documento'], unique=False)
    op.create_table('fragmento_farmacologico',
    sa.Column('id_fragmento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('numero_fragmento', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.ForeignKeyConstraint(['id_documento'], ['documento_farmacologico.id_documento'], ),
    sa.PrimaryKeyConstraint('id_fragmento')
    )
    op.create_index(op.f('ix_fragmento_farmacologico_id_documento'), 'fragmento_farmacologico', ['id_documento'], unique=False)
    op.create_index(op.f('ix_fragmento_farmacologico_id_fragmento'), 'fragmento_farmacologico', ['id_fragmento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fragmento_farmacologico_id_fragmento'), table_name='fragmento_farmacologico')
    op.drop_index(op.f('ix_fragmento_farmacologico_id_documento'), table_name='fragmento_farmacologico')
    op.drop_table('fragmento_farmacologico')
    op.drop_index(op.f('ix_documento_farmacologico_id_documento'), table_name='documento_farmacologico')
    op.drop_index(op.f('ix_documento_farmacologico_hash_archivo'), table_name='documento_farmacologico')
    op.drop_table('documento_farmacologico')
    # ### end Alembic commands ###
