"""sprint2 validacion_ia receta bloqueada

Revision ID: 844ad8e621e6
Revises: 076601647d34
Create Date: 2026-06-21 22:43:08.078817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '844ad8e621e6'
down_revision: Union[str, None] = '076601647d34'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validacion_ia',
    sa.Column('id_validacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_audio', sa.Integer(), nullable=True),
    sa.Column('nivel_riesgo', sa.Integer(), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('interacciones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contraindicaciones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duplicidades', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errores_dosis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inconsistencias_audio', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fuentes_rag', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_audio'], ['audio_clinico.id_audio'], ),
    sa.ForeignKeyConstraint(['id_receta'], ['prescriptions.id_receta'], ),
    sa.PrimaryKeyConstraint('id_validacion')
    )
    op.create_index(op.f('ix_validacion_ia_id_receta'), 'validacion_ia', ['id_receta'], unique=False)
    op.create_index(op.f('ix_validacion_ia_id_validacion'), 'validacion_ia', ['id_validacion'], unique=False)
    # server_default para no romper las filas existentes; el modelo usa default Python.
    op.add_column(
        'prescriptions',
        sa.Column('bloqueada', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('prescriptions', sa.Column('justificacion', sa.Text(), nullable=True))
    op.alter_column('prescriptions', 'bloqueada', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'justificacion')
    op.drop_column('prescriptions', 'bloqueada')
    op.drop_index(op.f('ix_validacion_ia_id_validacion'), table_name='validacion_ia')
    op.drop_index(op.f('ix_validacion_ia_id_receta'), table_name='validacion_ia')
    op.drop_table('validacion_ia')
    # ### end Alembic commands ###
