"""sprint2 audio_clinico alerta_clinica nivel_riesgo

Revision ID: 905aceff5f41
Revises: a7b8c9d0e1f2
Create Date: 2026-06-21 21:53:48.524009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905aceff5f41'
down_revision: Union[str, None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_clinico',
    sa.Column('id_audio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('formato', sa.String(length=20), nullable=False),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.Column('transcripcion', sa.Text(), nullable=True),
    sa.Column('estado_procesamiento', sa.String(length=20), nullable=False),
    sa.Column('fecha_grabacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_receta'], ['prescriptions.id_receta'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_audio')
    )
    op.create_index(op.f('ix_audio_clinico_id_audio'), 'audio_clinico', ['id_audio'], unique=False)
    op.create_table('alerta_clinica',
    sa.Column('id_alerta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_audio', sa.Integer(), nullable=True),
    sa.Column('tipo_alerta', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('recomendacion', sa.Text(), nullable=True),
    sa.Column('revisada', sa.Boolean(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_audio'], ['audio_clinico.id_audio'], ),
    sa.ForeignKeyConstraint(['id_receta'], ['prescriptions.id_receta'], ),
    sa.PrimaryKeyConstraint('id_alerta')
    )
    op.create_index(op.f('ix_alerta_clinica_id_alerta'), 'alerta_clinica', ['id_alerta'], unique=False)
    op.add_column('prescriptions', sa.Column('nivel_riesgo', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'nivel_riesgo')
    op.drop_index(op.f('ix_alerta_clinica_id_alerta'), table_name='alerta_clinica')
    op.drop_table('alerta_clinica')
    op.drop_index(op.f('ix_audio_clinico_id_audio'), table_name='audio_clinico')
    op.drop_table('audio_clinico')
    # ### end Alembic commands ###
