"""sprint2 dispensacion farmacia

Revision ID: 9211313640c0
Revises: 844ad8e621e6
Create Date: 2026-06-22 09:09:06.892276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9211313640c0'
down_revision: Union[str, None] = '844ad8e621e6'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispensacion',
    sa.Column('id_dispensacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_usuario_farmaceutico', sa.Integer(), nullable=True),
    sa.Column('codigo_verificacion', sa.String(length=128), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('fecha_dispensacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_receta'], ['prescriptions.id_receta'], ),
    sa.ForeignKeyConstraint(['id_usuario_farmaceutico'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_dispensacion')
    )
    op.create_index(op.f('ix_dispensacion_codigo_verificacion'), 'dispensacion', ['codigo_verificacion'], unique=True)
    op.create_index(op.f('ix_dispensacion_id_dispensacion'), 'dispensacion', ['id_dispensacion'], unique=False)
    op.create_index(op.f('ix_dispensacion_id_receta'), 'dispensacion', ['id_receta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispensacion_id_receta'), table_name='dispensacion')
    op.drop_index(op.f('ix_dispensacion_id_dispensacion'), table_name='dispensacion')
    op.drop_index(op.f('ix_dispensacion_codigo_verificacion'), table_name='dispensacion')
    op.drop_table('dispensacion')
    # ### end Alembic commands ###
