"""perf indices filtros y fks

Revision ID: 935bfa95db43
Revises: f9c35dc45a85
Create Date: 2026-06-22 11:34:01.695415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935bfa95db43'
down_revision: Union[str, None] = 'f9c35dc45a85'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerta_clinica_id_receta'), 'alerta_clinica', ['id_receta'], unique=False)
    op.create_index(op.f('ix_alerta_clinica_nivel'), 'alerta_clinica', ['nivel'], unique=False)
    op.create_index(op.f('ix_audio_clinico_id_receta'), 'audio_clinico', ['id_receta'], unique=False)
    op.create_index(op.f('ix_diagnoses_id_paciente'), 'diagnoses', ['id_paciente'], unique=False)
    op.create_index(op.f('ix_dispensacion_estado'), 'dispensacion', ['estado'], unique=False)
    op.create_index(op.f('ix_medications_estado'), 'medications', ['estado'], unique=False)
    op.create_index(op.f('ix_patients_activo'), 'patients', ['activo'], unique=False)
    op.create_index(op.f('ix_prescriptions_estado'), 'prescriptions', ['estado'], unique=False)
    op.create_index(op.f('ix_prescriptions_fecha_creacion'), 'prescriptions', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_prescriptions_id_paciente'), 'prescriptions', ['id_paciente'], unique=False)
    op.create_index(op.f('ix_users_activo'), 'users', ['activo'], unique=False)
    op.create_index(op.f('ix_users_id_rol'), 'users', ['id_rol'], unique=False)
    op.create_index(op.f('ix_validacion_ia_fecha_validacion'), 'validacion_ia', ['fecha_validacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validacion_ia_fecha_validacion'), table_name='validacion_ia')
    op.drop_index(op.f('ix_users_id_rol'), table_name='users')
    op.drop_index(op.f('ix_users_activo'), table_name='users')
    op.drop_index(op.f('ix_prescriptions_id_paciente'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_fecha_creacion'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_estado'), table_name='prescriptions')
    op.drop_index(op.f('ix_patients_activo'), table_name='patients')
    op.drop_index(op.f('ix_medications_estado'), table_name='medications')
    op.drop_index(op.f('ix_dispensacion_estado'), table_name='dispensacion')
    op.drop_index(op.f('ix_diagnoses_id_paciente'), table_name='diagnoses')
    op.drop_index(op.f('ix_audio_clinico_id_receta'), table_name='audio_clinico')
    op.drop_index(op.f('ix_alerta_clinica_nivel'), table_name='alerta_clinica')
    op.drop_index(op.f('ix_alerta_clinica_id_receta'), table_name='alerta_clinica')
    # ### end Alembic commands ###
