"""initial schema

Revision ID: d98788e947d9
Revises: 
Create Date: 2026-06-20 13:01:34.205078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98788e947d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_roles_id_rol'), 'roles', ['id_rol'], unique=False)
    op.create_table('users',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('numero_licencia', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_users_correo'), 'users', ['correo'], unique=True)
    op.create_index(op.f('ix_users_id_usuario'), 'users', ['id_usuario'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id_auditoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    op.create_index(op.f('ix_audit_logs_id_auditoria'), 'audit_logs', ['id_auditoria'], unique=False)
    op.create_table('medications',
    sa.Column('id_medicamento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('dosis', sa.String(length=100), nullable=True),
    sa.Column('presentacion', sa.String(length=100), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario_creacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_creacion'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_medicamento')
    )
    op.create_index(op.f('ix_medications_id_medicamento'), 'medications', ['id_medicamento'], unique=False)
    op.create_index(op.f('ix_medications_nombre'), 'medications', ['nombre'], unique=False)
    op.create_table('patients',
    sa.Column('id_paciente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario_creacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_creacion'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_index(op.f('ix_patients_correo'), 'patients', ['correo'], unique=False)
    op.create_index(op.f('ix_patients_documento'), 'patients', ['documento'], unique=False)
    op.create_index(op.f('ix_patients_id_paciente'), 'patients', ['id_paciente'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id_diagnostico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario_creacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['patients.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_usuario_creacion'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_diagnostico')
    )
    op.create_index(op.f('ix_diagnoses_codigo'), 'diagnoses', ['codigo'], unique=False)
    op.create_index(op.f('ix_diagnoses_id_diagnostico'), 'diagnoses', ['id_diagnostico'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id_receta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_diagnostico', sa.Integer(), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario_creacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_diagnostico'], ['diagnoses.id_diagnostico'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['patients.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_creacion'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_receta')
    )
    op.create_index(op.f('ix_prescriptions_id_receta'), 'prescriptions', ['id_receta'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('id_medicamento', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('dosis', sa.String(length=100), nullable=True),
    sa.Column('frecuencia', sa.String(length=100), nullable=True),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_medicamento'], ['medications.id_medicamento'], ),
    sa.ForeignKeyConstraint(['id_receta'], ['prescriptions.id_receta'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_index(op.f('ix_prescription_items_id_item'), 'prescription_items', ['id_item'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_items_id_item'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_prescriptions_id_receta'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_diagnoses_id_diagnostico'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_codigo'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_patients_id_paciente'), table_name='patients')
    op.drop_index(op.f('ix_patients_documento'), table_name='patients')
    op.drop_index(op.f('ix_patients_correo'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_medications_nombre'), table_name='medications')
    op.drop_index(op.f('ix_medications_id_medicamento'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_audit_logs_id_auditoria'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id_usuario'), table_name='users')
    op.drop_index(op.f('ix_users_correo'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id_rol'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
