"""block2 patients clinical_history diagnoses

Revision ID: f6dacd00ddbe
Revises: e1a2b3c4d5e6
Create Date: 2026-06-20 14:43:30.996733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6dacd00ddbe'
down_revision: Union[str, None] = 'e1a2b3c4d5e6'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_history',
    sa.Column('id_historial', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_evento', sa.DateTime(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['patients.id_paciente'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_index(op.f('ix_clinical_history_id_historial'), 'clinical_history', ['id_historial'], unique=False)
    op.add_column('diagnoses', sa.Column('id_usuario', sa.Integer(), nullable=False))
    op.add_column('diagnoses', sa.Column('codigo_cie10', sa.String(length=10), nullable=True))
    op.add_column('diagnoses', sa.Column('tipo', sa.String(length=20), nullable=False))
    op.add_column('diagnoses', sa.Column('observaciones', sa.Text(), nullable=True))
    op.add_column('diagnoses', sa.Column('fecha_diagnostico', sa.DateTime(), nullable=False))
    op.add_column('diagnoses', sa.Column('activo', sa.Boolean(), nullable=False))
    op.drop_index('ix_diagnoses_codigo', table_name='diagnoses')
    op.create_index(op.f('ix_diagnoses_codigo_cie10'), 'diagnoses', ['codigo_cie10'], unique=False)
    op.drop_constraint('diagnoses_id_usuario_creacion_fkey', 'diagnoses', type_='foreignkey')
    op.create_foreign_key(None, 'diagnoses', 'users', ['id_usuario'], ['id_usuario'])
    op.drop_column('diagnoses', 'fecha_creacion')
    op.drop_column('diagnoses', 'codigo')
    op.drop_column('diagnoses', 'notas')
    op.drop_column('diagnoses', 'id_usuario_creacion')
    op.drop_column('diagnoses', 'estado')
    op.add_column('patients', sa.Column('ci', sa.String(length=20), nullable=False))
    op.add_column('patients', sa.Column('sexo', sa.String(length=20), nullable=False))
    op.add_column('patients', sa.Column('peso_kg', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('patients', sa.Column('funcion_renal', sa.String(length=20), nullable=False))
    op.add_column('patients', sa.Column('funcion_hepatica', sa.String(length=20), nullable=False))
    op.add_column('patients', sa.Column('alergias', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('antecedentes_medicos', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('observaciones', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('activo', sa.Boolean(), nullable=False))
    op.add_column('patients', sa.Column('fecha_registro', sa.DateTime(), nullable=False))
    op.add_column('patients', sa.Column('id_usuario_registro', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('id_usuario_actualizacion', sa.Integer(), nullable=True))
    op.alter_column('patients', 'fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index('ix_patients_documento', table_name='patients')
    op.create_index(op.f('ix_patients_ci'), 'patients', ['ci'], unique=True)
    op.drop_constraint('patients_id_usuario_creacion_fkey', 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'users', ['id_usuario_registro'], ['id_usuario'])
    op.create_foreign_key(None, 'patients', 'users', ['id_usuario_actualizacion'], ['id_usuario'])
    op.drop_column('patients', 'documento')
    op.drop_column('patients', 'genero')
    op.drop_column('patients', 'fecha_creacion')
    op.drop_column('patients', 'id_usuario_creacion')
    op.drop_column('patients', 'direccion')
    op.drop_column('patients', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('id_usuario_creacion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('genero', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('documento', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key('patients_id_usuario_creacion_fkey', 'patients', 'users', ['id_usuario_creacion'], ['id_usuario'])
    op.drop_index(op.f('ix_patients_ci'), table_name='patients')
    op.create_index('ix_patients_documento', 'patients', ['documento'], unique=False)
    op.alter_column('patients', 'fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('patients', 'id_usuario_actualizacion')
    op.drop_column('patients', 'id_usuario_registro')
    op.drop_column('patients', 'fecha_registro')
    op.drop_column('patients', 'activo')
    op.drop_column('patients', 'observaciones')
    op.drop_column('patients', 'antecedentes_medicos')
    op.drop_column('patients', 'alergias')
    op.drop_column('patients', 'funcion_hepatica')
    op.drop_column('patients', 'funcion_renal')
    op.drop_column('patients', 'peso_kg')
    op.drop_column('patients', 'sexo')
    op.drop_column('patients', 'ci')
    op.add_column('diagnoses', sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('diagnoses', sa.Column('id_usuario_creacion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('diagnoses', sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('diagnoses', sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('diagnoses', sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'diagnoses', type_='foreignkey')
    op.create_foreign_key('diagnoses_id_usuario_creacion_fkey', 'diagnoses', 'users', ['id_usuario_creacion'], ['id_usuario'])
    op.drop_index(op.f('ix_diagnoses_codigo_cie10'), table_name='diagnoses')
    op.create_index('ix_diagnoses_codigo', 'diagnoses', ['codigo'], unique=False)
    op.drop_column('diagnoses', 'activo')
    op.drop_column('diagnoses', 'fecha_diagnostico')
    op.drop_column('diagnoses', 'observaciones')
    op.drop_column('diagnoses', 'tipo')
    op.drop_column('diagnoses', 'codigo_cie10')
    op.drop_column('diagnoses', 'id_usuario')
    op.drop_index(op.f('ix_clinical_history_id_historial'), table_name='clinical_history')
    op.drop_table('clinical_history')
    # ### end Alembic commands ###
