"""sprint2 patient id_usuario portal

Revision ID: f8088e79bdf3
Revises: 9211313640c0
Create Date: 2026-06-22 09:27:48.303041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8088e79bdf3'
down_revision: Union[str, None] = '9211313640c0'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'patients', ['id_usuario'])
    op.create_foreign_key(None, 'patients', 'users', ['id_usuario'], ['id_usuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'id_usuario')
    # ### end Alembic commands ###
