"""sprint2 auditoria duracion_ms

Revision ID: f9c35dc45a85
Revises: f8088e79bdf3
Create Date: 2026-06-22 10:57:10.347327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c35dc45a85'
down_revision: Union[str, None] = 'f8088e79bdf3'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id_auditoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=80), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=50), nullable=True),
    sa.Column('id_registro', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('ip_origen', sa.String(length=50), nullable=True),
    sa.Column('fecha_accion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    op.create_index(op.f('ix_auditoria_accion'), 'auditoria', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_fecha_accion'), 'auditoria', ['fecha_accion'], unique=False)
    op.create_index(op.f('ix_auditoria_id_auditoria'), 'auditoria', ['id_auditoria'], unique=False)
    op.create_index(op.f('ix_auditoria_id_usuario'), 'auditoria', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_auditoria_modulo'), 'auditoria', ['modulo'], unique=False)
    op.add_column('validacion_ia', sa.Column('duracion_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validacion_ia', 'duracion_ms')
    op.drop_index(op.f('ix_auditoria_modulo'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_id_usuario'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_id_auditoria'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_fecha_accion'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_accion'), table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
